/*******************************************************************************
  System Initialization File

  File Name:
    initialization.c

  Summary:
    This file contains source code necessary to initialize the system.

  Description:
    This file contains source code necessary to initialize the system.  It
    implements the "SYS_Initialize" function, defines the configuration bits,
    and allocates any necessary global system resources,
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *******************************************************************************/
// DOM-IGNORE-END

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************
#include "configuration.h"
#include "definitions.h"
#include "device.h"


// ****************************************************************************
// ****************************************************************************
// Section: Configuration Bits
// ****************************************************************************
// ****************************************************************************
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQ = 0x1U
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQBAR = 0xfffeU
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_EWOFFSET = CYC8
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQ = 0x2U
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQBAR = 0xfffdU
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1A_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_EWOFFSET = CYC8




// *****************************************************************************
// *****************************************************************************
// Section: Driver Initialization Data
// *****************************************************************************
// *****************************************************************************
/* Following MISRA-C rules are deviated in the below code block */
/* MISRA C-2012 Rule 7.2 - Deviation record ID - H3_MISRAC_2012_R_7_2_DR_1 */
/* MISRA C-2012 Rule 11.1 - Deviation record ID - H3_MISRAC_2012_R_11_1_DR_1 */
/* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
/* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */
// <editor-fold defaultstate="collapsed" desc="DRV_SPI Instance 0 Initialization Data">

/* SPI Client Objects Pool */
static DRV_SPI_CLIENT_OBJ drvSPI0ClientObjPool[DRV_SPI_CLIENTS_NUMBER_IDX0];

/* SPI Transfer Objects Pool */
static DRV_SPI_TRANSFER_OBJ drvSPI0TransferObjPool[DRV_SPI_QUEUE_SIZE_IDX0];

/* SPI PLIB Interface Initialization */
static const DRV_SPI_PLIB_INTERFACE drvSPI0PlibAPI = {

    /* SPI PLIB Setup */
    .setup = (DRV_SPI_PLIB_SETUP)SERCOM2_SPI_TransferSetup,

    /* SPI PLIB WriteRead function */
    .writeRead = (DRV_SPI_PLIB_WRITE_READ)SERCOM2_SPI_WriteRead,

    /* SPI PLIB Transfer Status function */
    .isTransmitterBusy = (DRV_SPI_PLIB_TRANSMITTER_IS_BUSY)SERCOM2_SPI_IsTransmitterBusy,

    /* SPI PLIB Callback Register */
    .callbackRegister = (DRV_SPI_PLIB_CALLBACK_REGISTER)SERCOM2_SPI_CallbackRegister,
};

static const uint32_t drvSPI0remapDataBits[]= { 0x0, 0x1, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU };
static const uint32_t drvSPI0remapClockPolarity[] = { 0x0, 0x20000000 };
static const uint32_t drvSPI0remapClockPhase[] = { 0x10000000, 0x0 };

static const DRV_SPI_INTERRUPT_SOURCES drvSPI0InterruptSources =
{
    /* Peripheral has more than one interrupt vector */
    .isSingleIntSrc                        = false,

    /* Peripheral interrupt lines */
   .intSources.multi.spiTxReadyInt     = (int32_t)SERCOM2_0_IRQn,
   .intSources.multi.spiTxCompleteInt  = (int32_t)SERCOM2_1_IRQn,
   .intSources.multi.spiRxInt          = (int32_t)SERCOM2_2_IRQn,
    /* DMA Tx interrupt line */
    .intSources.multi.dmaTxChannelInt      = (int32_t)DMAC_TCMPL0_IRQn,
    /* DMA Rx interrupt line */
    .intSources.multi.dmaRxChannelInt      = (int32_t)DMAC_TCMPL1_IRQn,
};

/* SPI Driver Initialization Data */
static const DRV_SPI_INIT drvSPI0InitData =
{
    /* SPI PLIB API */
    .spiPlib = &drvSPI0PlibAPI,

    .remapDataBits = drvSPI0remapDataBits,

    .remapClockPolarity = drvSPI0remapClockPolarity,

    .remapClockPhase = drvSPI0remapClockPhase,

    /* SPI Number of clients */
    .numClients = DRV_SPI_CLIENTS_NUMBER_IDX0,

    /* SPI Client Objects Pool */
    .clientObjPool = (uintptr_t)&drvSPI0ClientObjPool[0],

    /* DMA Channel for Transmit */
    .dmaChannelTransmit = DRV_SPI_XMIT_DMA_CH_IDX0,

    /* DMA Channel for Receive */
    .dmaChannelReceive  = DRV_SPI_RCV_DMA_CH_IDX0,

    /* SPI Transmit Register */
    .spiTransmitAddress =  (void *)&(SERCOM2_REGS->SPI.SERCOM_DATA),

    /* SPI Receive Register */
    .spiReceiveAddress  = (void *)&(SERCOM2_REGS->SPI.SERCOM_DATA),

    /* SPI Queue Size */
    .transferObjPoolSize = DRV_SPI_QUEUE_SIZE_IDX0,

    /* SPI Transfer Objects Pool */
    .transferObjPool = (uintptr_t)&drvSPI0TransferObjPool[0],

    /* SPI interrupt sources (SPI peripheral and DMA) */
    .interruptSources = &drvSPI0InterruptSources,
};
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="DRV_USART Instance 0 Initialization Data">

static DRV_USART_CLIENT_OBJ drvUSART0ClientObjPool[DRV_USART_CLIENTS_NUMBER_IDX0];

/* USART transmit/receive transfer objects pool */
static DRV_USART_BUFFER_OBJ drvUSART0BufferObjPool[DRV_USART_QUEUE_SIZE_IDX0];

static const DRV_USART_PLIB_INTERFACE drvUsart0PlibAPI = {
    .readCallbackRegister = (DRV_USART_PLIB_READ_CALLBACK_REG)SERCOM3_USART_ReadCallbackRegister,
    .read_t = (DRV_USART_PLIB_READ)SERCOM3_USART_Read,
    .readIsBusy = (DRV_USART_PLIB_READ_IS_BUSY)SERCOM3_USART_ReadIsBusy,
    .readCountGet = (DRV_USART_PLIB_READ_COUNT_GET)SERCOM3_USART_ReadCountGet,
    .readAbort = (DRV_USART_PLIB_READ_ABORT)SERCOM3_USART_ReadAbort,
    .writeCallbackRegister = (DRV_USART_PLIB_WRITE_CALLBACK_REG)SERCOM3_USART_WriteCallbackRegister,
    .write_t = (DRV_USART_PLIB_WRITE)SERCOM3_USART_Write,
    .writeIsBusy = (DRV_USART_PLIB_WRITE_IS_BUSY)SERCOM3_USART_WriteIsBusy,
    .writeCountGet = (DRV_USART_PLIB_WRITE_COUNT_GET)SERCOM3_USART_WriteCountGet,
    .errorGet = (DRV_USART_PLIB_ERROR_GET)SERCOM3_USART_ErrorGet,
    .serialSetup = (DRV_USART_PLIB_SERIAL_SETUP)SERCOM3_USART_SerialSetup
};

static const uint32_t drvUsart0remapDataWidth[] = { 0x5, 0x6, 0x7, 0x0, 0x1 };
static const uint32_t drvUsart0remapParity[] = { 0x2, 0x0, 0x80000, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU };
static const uint32_t drvUsart0remapStopBits[] = { 0x0, 0xFFFFFFFFU, 0x40 };
static const uint32_t drvUsart0remapError[] = { 0x4, 0x0, 0x2 };

static const DRV_USART_INTERRUPT_SOURCES drvUSART0InterruptSources =
{
    /* Peripheral has more than one interrupt vector */
    .isSingleIntSrc                        = false,

    /* Peripheral interrupt lines */
   .intSources.multi.usartTxCompleteInt   = (int32_t)SERCOM3_1_IRQn,
   .intSources.multi.usartTxReadyInt      = (int32_t)SERCOM3_0_IRQn,
   .intSources.multi.usartRxCompleteInt   = (int32_t)SERCOM3_2_IRQn,
   .intSources.multi.usartErrorInt        = (int32_t)SERCOM3_6_IRQn,        
    /* DMA Tx interrupt line */
    .intSources.multi.dmaTxChannelInt      = (int32_t)DMAC_TCMPL2_IRQn,
};

static const DRV_USART_INIT drvUsart0InitData =
{
    .usartPlib = &drvUsart0PlibAPI,

    /* USART Number of clients */
    .numClients = DRV_USART_CLIENTS_NUMBER_IDX0,

    /* USART Client Objects Pool */
    .clientObjPool = (uintptr_t)&drvUSART0ClientObjPool[0],

    .dmaChannelTransmit = DRV_USART_XMIT_DMA_CH_IDX0,

    .usartTransmitAddress = (void *)&(SERCOM3_REGS->USART.SERCOM_DATA),

    .dmaChannelReceive = SYS_DMA_CHANNEL_NONE,

    /* Combined size of transmit and receive buffer objects */
    .bufferObjPoolSize = DRV_USART_QUEUE_SIZE_IDX0,

    /* USART transmit and receive buffer buffer objects pool */
    .bufferObjPool = (uintptr_t)&drvUSART0BufferObjPool[0],

    .interruptSources = &drvUSART0InterruptSources,

    .remapDataWidth = drvUsart0remapDataWidth,

    .remapParity = drvUsart0remapParity,

    .remapStopBits = drvUsart0remapStopBits,

    .remapError = drvUsart0remapError,

    .dataWidth = DRV_USART_DATA_8_BIT,
};

// </editor-fold>



// *****************************************************************************
// *****************************************************************************
// Section: System Data
// *****************************************************************************
// *****************************************************************************
/* Structure to hold the object handles for the modules in the system. */
SYSTEM_OBJECTS sysObj;

// *****************************************************************************
// *****************************************************************************
// Section: Library/Stack Initialization Data
// *****************************************************************************
// *****************************************************************************


// *****************************************************************************
// *****************************************************************************
// Section: System Initialization
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: Local initialization functions
// *****************************************************************************
// *****************************************************************************

/*******************************************************************************
  Function:
    void STDIO_BufferModeSet ( void )

  Summary:
    Sets the buffering mode for stdin and stdout

  Remarks:
 ********************************************************************************/
static void STDIO_BufferModeSet(void)
{
    /* MISRAC 2012 deviation block start */
    /* MISRA C-2012 Rule 21.6 deviated 2 times in this file.  Deviation record ID -  H3_MISRAC_2012_R_21_6_DR_3 */

    /* Make stdin unbuffered */
    setbuf(stdin, NULL);

    /* Make stdout unbuffered */
    setbuf(stdout, NULL);
    /* MISRAC 2012 deviation block end */
}


/* MISRAC 2012 deviation block end */

/*******************************************************************************
  Function:
    void SYS_Initialize ( void *data )

  Summary:
    Initializes the board, services, drivers, application and other modules.

  Remarks:
 */

void SYS_Initialize ( void* data )
{

    /* MISRAC 2012 deviation block start */
    /* MISRA C-2012 Rule 2.2 deviated in this file.  Deviation record ID -  H3_MISRAC_2012_R_2_2_DR_1 */

    STDIO_BufferModeSet();

  
    PORT_Initialize();

    CLOCK_Initialize();




    SERCOM3_USART_Initialize();

    SERCOM2_SPI_Initialize();

    SERCOM1_I2C_Initialize();

    EVSYS_Initialize();

	//SYSTICK_TimerInitialize();
    DMAC_Initialize();

    PM_Initialize();

    SERCOM4_USART_Initialize();
    
    CAN0_Initialize();

    ADC_Initialize();    
    
    EIC_Initialize();

	BSP_Initialize();
    
    TCC1_PWMInitialize();

    TCC0_PWMInitialize();

    TCC3_PWMInitialize();


    /* MISRAC 2012 deviation block start */
    /* Following MISRA-C rules deviated in this block  */
    /* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
    /* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */

    /* Initialize SPI0 Driver Instance */
    sysObj.drvSPI0 = DRV_SPI_Initialize(DRV_SPI_INDEX_0, (SYS_MODULE_INIT *)&drvSPI0InitData);

    sysObj.drvUsart0 = DRV_USART_Initialize(DRV_USART_INDEX_0, (SYS_MODULE_INIT *)&drvUsart0InitData);



    NVIC_Initialize();
    /* MISRAC 2012 deviation block end */
    //APP_Initialize();





    /* MISRAC 2012 deviation block end */
}

/*******************************************************************************
 End of File
*/
